Document: gl4es
Title: Debian gl4es Manual
Author: <insert document author here>
Abstract: This manual describes what gl4es is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/gl4es/gl4es.sgml.gz

Format: postscript
Files: /usr/share/doc/gl4es/gl4es.ps.gz

Format: text
Files: /usr/share/doc/gl4es/gl4es.text.gz

Format: HTML
Index: /usr/share/doc/gl4es/html/index.html
Files: /usr/share/doc/gl4es/html/*.html
